%% 基本信息输入（执行一次）
% 创建 NWB 文件
nwb = NwbFile( ...
    'session_description', 'Multi-site LFP activity recorded in temporal lobe epilepsy rats',...
    'identifier', 'RatB6_2023_05_13', ... % 每个文件单独修改
    'session_start_time', datetime(2023, 5, 13, 0, 0, 0, 'TimeZone', 'local'), ... % 每个文件单独修改
    'timestamps_reference_time', datetime(2023, 5, 13, 0, 0, 0, 'TimeZone', 'local'), ... % 每个文件单独修改
    'general_session_id', 'RatB6_2023_05_13', ...  % 每个文件单独修改
    'general_institution', 'Zhejiang University');

% 创建对象
subject = types.core.Subject( ...
    'subject_id', 'RatB6', ... % 每只鼠单独修改
    'age', 'P2M', ...
    'species', 'Rattus norvegicus', ...
    'sex', 'M', ...
    'weight', '300-350g', ...
    'description', 'Sprague-Dawley' ...
);
nwb.general_subject = subject;

% 创建电极表
numShanks = 12;
numChannelsPerShank = 1;
 
ElectrodesDynamicTable = types.hdmf_common.DynamicTable(...
    'colnames', {'location', 'group', 'group_name', 'label'}, ...
    'description', 'all electrodes');
 
Device = types.core.Device(...
    'description', 'Depth electrodes', ...
    'manufacturer', 'Formvar-insulated nichrome' ...
);
nwb.general_devices.set('implant', Device);

Shankname = {'R_SUB','R_DG','R_CA1','R_CA3','R_AMD','R_ANT','L_SUB','L_DG','L_CA1','L_CA3','L_AMD','L_ANT'};
% R&Z组相反
Electrode_Location = {'AP:-6.0mm,ML:+3.0mm,DV:-2.5mm', 'AP:-5.0mm,ML:+3.2mm,DV:-3.2mm',...
                                          'AP:-4.2mm,ML:+3.0mm,DV:-2.2mm', 'AP:-3.7mm,ML:+4.0mm,DV:-2.8mm',...
                                          'AP:-2.4mm,ML:+4.8mm,DV:-8.0mm', 'AP:-1.2mm,ML:+2.0mm,DV:-5.6mm',...
                                          'AP:-6.0mm,ML:-3.0mm,DV:-2.5mm','AP:-5.0mm,ML:-3.2mm,DV:-3.2mm',...
                                          'AP:-4.2mm,ML:-3.0mm,DV:-2.2mm', 'AP:-3.7mm,ML:-4.0mm,DV:-2.8mm',...
                                          'AP:-2.4mm,ML:-4.8mm,DV:-8.0mm', 'AP:-1.2mm,ML:-2.0mm,DV:-5.6mm'};

for iShank = 1:numShanks
    shankGroupName = char(Shankname(iShank));
    EGroup = types.core.ElectrodeGroup( ...
        'description', sprintf('electrode group for %s', shankGroupName), ...
        'location', shankGroupName, ...
        'device', types.untyped.SoftLink(Device) ...
    );
    
    nwb.general_extracellular_ephys.set(shankGroupName, EGroup);
    
    ElectrodesDynamicTable.addRow( ...
            'location', char(Electrode_Location(iShank)), ...
            'group', types.untyped.ObjectView(EGroup), ...
            'group_name', shankGroupName, ...
            'label', sprintf('%s-electrode%d', shankGroupName, iShank));
   
end

ElectrodesDynamicTable.toTable()
nwb.general_extracellular_ephys_electrodes = ElectrodesDynamicTable;

% 创建电压数据表
electrode_table_region = types.hdmf_common.DynamicTableRegion( ...
    'table', types.untyped.ObjectView(ElectrodesDynamicTable), ...
    'description', 'all electrodes', ...
    'data', (0:length(ElectrodesDynamicTable.id.data)-1)');

ecephys_module = types.core.ProcessingModule(...
    'description', 'extracellular electrophysiology');

%% 多片段数据导入
ReadFile ='E:\ZJU_BME_PhD\Epilepsy\Scientific Data\fragments\mat\B6\Early_stage\2023_5_13_ictal_4\*.mat';
ReadFilePath = 'E:\ZJU_BME_PhD\Epilepsy\Scientific Data\fragments\mat\B6\Early_stage\2023_5_13_ictal_4\';
FileList = dir(ReadFile);
filenum = length(FileList);

for i = 1:filenum
    fileName = FileList(i).name;
    l = length(fileName);
    load([ReadFilePath,fileName])

    fData_compressed=types.untyped.DataPipe( ...
        'data', data, ... 
        'compressionLevel', 3, ...
        'chunkSize', [1 1000], ...
        'axis', 1);

    electrical_series = types.core.ElectricalSeries( ...
        'starting_time', 0.0, ... % seconds
        'starting_time_rate', 1000., ... % Hz
        'data', fData_compressed, ...
        'electrodes', electrode_table_region, ...
        'description', 'Raw acquisition at early stage', ... % 每个阶段单独修改
        'data_unit', 'microvolts');

    nwb.acquisition.set(fileName(1:l-4), electrical_series); 
    fprintf('%s done.\n', fileName(1:l-4));
end

%% 结尾部分（执行一次）
% 写入 NWB 文件
nwbExport(nwb, 'sub-B6_ses-20230513-ictal4_ecephys.nwb') % 每个文件单独修改